### ISSUE TITLE
Emitir informes de pedidos que permitan establecer que pedidos han llegado a tiempo y que pedidos se han retrasado

### ISSUE THREAD

**Issue by Froznar** [Froznar/IS2-Gesti-n-de-Inventarios-final#24]
Tareas:
- Se debe poder mostrar los pedidos pendientes al iniciarse el mes.
- Se debe poder mostrar los pedidos emitidos durante el mes.
- Se debe poder mostrar los pedidos recibidos en el mes.
- Se debe poder mostrar los pedidos pendientes al final del mes.
- Se debe poder mostrar los pedidos recibidos a tiempo.
- Se debe poder mostrar los pedidos recibidos con retraso(Cantidad y porcentaje).

**Comment by Froznar** [comment]
me concentrare en el usuario administrador, les encargo este issue.

**Comment by jonalv100** [comment]
Este issue está terminado, solo faltaría en la parte de FE usarlo para mostrar los informes.
